# This is a basic workflow to help you get started with Actions

name: Build and deploy microfrontend
# Controls when the workflow will run
on: [pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          cache: "yarn"

      - run: yarn install
      - run: yarn build

      - name: copy everything to output folder
        run: sudo mv ./packages/app1/dist/*.* ./packages/root-config/dist/ && sudo mv ./packages/app2/dist/*.* ./packages/root-config/dist/

      # - name: "Deploy to Vercel"
      #   id: Vercel
      #   run: |
      #     npx vercel --token ${VERCEL_TOKEN} --public
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Vercel Action
        id: Vercel
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required

      - name: Create importmap.json
        run: node ./create-importmap.js {{ Vercel.outputs.preview-url }}
