# This is a basic workflow to help you get started with Actions

name: Build and deploy microfrontend
# Controls when the workflow will run
on: [pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: create public
        run: mkdir -p ./public

      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          cache: "yarn"

      - run: yarn install
      - run: yarn build
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: copy everything to dist
        run: sudo mv ./packages/root-config/dist/*.* ./public/ && sudo mv ./packages/app1/dist/*.* ./public/ && sudo mv ./packages/app2/dist/*.* ./public/

      - name: "Deploy to Vercel"
        id: Vercel
        run: |
          npx vercel --token ${VERCEL_TOKEN}  --build-env PR_NUMBER=${{ github.event.pull_request.number }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Create importmap.json
        run: node ./create-importmap.js
