# This is a basic workflow to help you get started with Actions

name: Deploy applications to s34

# Controls when the workflow will run

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4

      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command

      - name: create dist
        run: mkdir -p ./dist/${{ steps.branch-name.outputs.current_branch }}/

      - name: create projects folders
        run: mkdir -p ./dist/${{ steps.branch-name.outputs.current_branch }}/root-config && mkdir -p ./dist/${{ steps.branch-name.outputs.current_branch }}/app1 && mkdir -p ./dist/${{ steps.branch-name.outputs.current_branch }}/app2

      - name: copy everything to dist
        run: mv ./packages/root-config/dist/*.* ./dist/${{ steps.branch-name.outputs.current_branch }}/root-config && mv ./packages/app1/dist/*.* ./dist/${{ steps.branch-name.outputs.current_branch }}/app1 && mv ./packages/app2/dist/*.* ./dist/${{ steps.branch-name.outputs.current_branch }}/app2

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: mftest-mario
          source_dir: "dist"
