# This is a basic workflow to help you get started with Actions

name: Build and deploy microfrontend

# Controls when the workflow will run

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: create dist
        run: mkdir -p ./dist/${{ github.event.pull_request.number }}/

      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command

      - name: create projects folders
        run: mkdir -p ./dist/${{ github.event.pull_request.number }}/root-config && mkdir -p ./dist/${{ github.event.pull_request.number }}/app1 && mkdir -p ./dist/${{ github.event.pull_request.number }}/app2

      - name: copy everything to dist
        run: sudo mv ./packages/root-config/dist/*.* ./dist/${{ github.event.pull_request.number }}/root-config && sudo mv ./packages/app1/dist/*.* ./dist/${{ github.event.pull_request.number }}/app1 && sudo mv ./packages/app2/dist/*.* ./dist/${{ github.event.pull_request.number }}/app2

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: mftest-mario
          source_dir: "dist"
          destination_dir: "microfrontend"
